timezone: Europe/Moscow

url: https://artsiom.mezin.eu
enforce_ssl: www.artsiom.mezin.eu

safe: true
markdown: kramdown
highlighter: true

exclude: [package.json, .gitignore, .editorconfig, node_modules, README.md]

title: ""
description: ""
